### ISSUE TITLE
Fix  registry dependabot issues

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1030]
## Which area/kind this issue is related to?

- [x] registry-operator https://github.com/devfile/api/issues/1081
- [x] registry-support https://github.com/devfile/registry-support/pull/169
- [x] library - This issue https://github.com/devfile/library/pull/165 should fix most of the findings

## Issue Description

The registry issues seem to be related to the use of an old oras dependency.   The risk seems low since we do not use the affected code paths and require the registry to be deployed in a trusted environment but we should make it a point to update out-of-date dependencies regardless

Target Date:   03/31/23

**Comment by kim-tsao** [comment]
track status in user stories
