### ISSUE TITLE
Devfile lifecycle management process

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1063]
## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

We need to define a process that details what the expected responsibilities are from the stack providers and devfile team to onboard, maintain and deprecate a devfile stack/sample over the course of its lifespan.  

**Detailed description:**

## Describe the solution you'd like

We will need the following to be in place:

### Documentation:
- [x]  https://github.com/devfile/api/issues/1066

### Handling Deprecation:

**Viewer**
- [x] https://github.com/devfile/api/issues/964
- [x] https://github.com/devfile/api/issues/1064

**Registry Support**
- [x] https://github.com/devfile/api/issues/959

**Registry Library**
- [x] https://github.com/devfile/api/issues/1065

**Comment by thepetk** [comment]
closing as DONE as all the child issues have been completed
