### ISSUE TITLE
Documentation Improvements from DevTools Week

### ISSUE THREAD

**Issue by jasperchui** [devfile/api#1077]
Documentation improvements identified from Devtools Week.

## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?

All

## Issue details

- [x] #1068 Guide on innerloop vs outerloop setups
- [x] #1076 Add a community page
- [x] #1071 Guide on packaging devfiles
- [x] #1070 Create tutorial for registry devfile stack creation

**What mistake did you find / what is missing in the documentation?**

**Comment by jasperchui** [comment]
Issues have been addressed. Closing EPIC.
