### ISSUE TITLE
Add devfile 2.2 outer-loop support to existing stacks - Part 2

### ISSUE THREAD

**Issue by elsony** [devfile/api#1085]
## Which area this feature is related to?
/area registry

## Which functionality do you think we should add?
Add devfile 2.2 outer-loop support to existing stacks.

# Why is this needed? Is your feature request related to a problem?
To provide examples of how to implement devfile 2.2

# Detailed description:
Provide devfile 2.2 outer-loop support to existing stacks (that the Devfile team owns):

- [x] https://github.com/devfile/api/issues/1317
- [x] https://github.com/devfile/api/issues/1318
- [ ] ~.Net~ (as discussed on Oct 27, 2023, this is not needed for now)
- [x] https://github.com/devfile/api/issues/1319

When implementing, we want to keep the stacks with different schema versions 2.1/2.2 using multi-version support in the registry.
**Why is this needed? Is your feature request related to a problem?**

## Describe alternatives you've considered
N/A

## Additional context
This item is a continuation of https://github.com/devfile/api/issues/757.

**Comment by maysunfaisal** [comment]
- Maybe needs to be an EPIC
- Current Samples need to be updated
-

**Comment by rm3l** [comment]
@maysunfaisal Since this epic is part of the Q4 goals, any ideas on how this should be broken down? (I am preparing the upcoming refinement call).
From the issue description, I tried to understand the current Devfile 2.2 outer-loop support for each stack and here is what I found:

<table>
<tr>
 <th>Stack
 <th>Devfile 2.1.0
 <th>Devfile 2.2.0
<tr>
 <td>dotnet50
 <td>yes
 <td>NO
<tr>
 <td>dotnet60
 <td>yes
 <td>NO
<tr>
 <td>dotnetcore31
 <td>yes
 <td>NO
<tr>
 <td>go
 <td>yes
 <td>yes
<tr>
 <td>java-maven
 <td>yes
 <td>NO
<tr>
 <td>java-openliberty
 <td>yes
 <td>NO
<tr>
 <td>java-openliberty-gradle
 <td>yes
 <td>NO
<tr>
 <td>java-quarkus
 <td>yes
 <td>NO
<tr>
 <td>java-springboot
 <td>yes
 <td>yes
<tr>
 <td>java-vertx
 <td>yes
 <td>NO
<tr>
 <td>java-websphereliberty
 <td>yes
 <td>NO
<tr>
 <td>java-websphereliberty-gradle
 <td>yes
 <td>NO
<tr>
 <td>java-wildfly
 <td>yes
 <td>yes
<tr>
 <td>java-wildfly-bootable-jar
 <td>yes
 <td>NO
<tr>
 <td>nodejs
 <td>yes
 <td>NO
<tr>
 <td>nodejs-angular
 <td>yes
 <td>yes
<tr>
 <td>nodejs-nextjs
 <td>yes
 <td>yes
<tr>
 <td>nodejs-nuxtjs
 <td>yes
 <td>yes
<tr>
 <td>nodejs-react
 <td>yes
 <td>yes
<tr>
 <td>nodejs-svelte
 <td>yes
 <td>yes
<tr>
 <td>nodejs-vue
 <td>yes
 <td>yes
<tr>
 <td>php-laravel
 <td>yes
 <td>yes
<tr>
 <td>python
 <td>yes
 <td>yes
<tr>
 <td>python-django
 <td>yes
 <td>NO
<tr>
 <td>udi
 <td>no
 <td>yes
</table>

<details>
<summary>Details</summary>

```
stacks/dotnet50/devfile.yaml: 2.1.0

stacks/dotnet60/devfile.yaml: 2.1.0

stacks/dotnetcore31/devfile.yaml: 2.1.0

stacks/go/1.0.2/devfile.yaml: 2.1.0
stacks/go/1.1.0/devfile.yaml: 2.1.0
stacks/go/2.0.0/devfile.yaml: 2.2.0
stacks/go/2.1.0/devfile.yaml: 2.2.0

stacks/java-maven/1.2.0/devfile.yaml: 2.1.0
stacks/java-maven/1.3.0/devfile.yaml: 2.1.0

stacks/java-openliberty/devfile.yaml: 2.1.0

stacks/java-openliberty-gradle/devfile.yaml: 2.1.0

stacks/java-quarkus/devfile.yaml: 2.1.0

stacks/java-springboot/1.2.0/devfile.yaml: 2.1.0
stacks/java-springboot/1.3.0/devfile.yaml: 2.1.0
stacks/java-springboot/2.0.0/devfile.yaml: 2.2.0
stacks/java-springboot/2.1.0/devfile.yaml: 2.2.0

stacks/java-vertx/devfile.yaml: 2.1.0

stacks/java-websphereliberty/devfile.yaml: 2.1.0

stacks/java-websphereliberty-gradle/devfile.yaml: 2.1.0

stacks/java-wildfly/1.1.0/devfile.yaml: 2.1.0
stacks/java-wildfly/2.0.0/devfile.yaml: 2.2.0

stacks/java-wildfly-bootable-jar/devfile.yaml: 2.1.0

stacks/nodejs/2.1.1/devfile.yaml: 2.1.0
stacks/nodejs/2.2.0/devfile.yaml: 2.1.0

stacks/nodejs-angular/2.0.2/devfile.yaml: 2.1.0
stacks/nodejs-angular/2.1.0/devfile.yaml: 2.1.0
stacks/nodejs-angular/2.2.0/devfile.yaml: 2.2.0

stacks/nodejs-nextjs/1.0.3/devfile.yaml: 2.1.0
stacks/nodejs-nextjs/1.1.0/devfile.yaml: 2.1.0
stacks/nodejs-nextjs/1.2.0/devfile.yaml: 2.2.0

stacks/nodejs-nuxtjs/1.0.3/devfile.yaml: 2.1.0
stacks/nodejs-nuxtjs/1.1.0/devfile.yaml: 2.1.0
stacks/nodejs-nuxtjs/1.2.0/devfile.yaml: 2.2.0

stacks/nodejs-react/2.0.2/devfile.yaml: 2.1.0
stacks/nodejs-react/2.1.0/devfile.yaml: 2.1.0
stacks/nodejs-react/2.2.0/devfile.yaml: 2.2.0

stacks/nodejs-svelte/1.0.3/devfile.yaml: 2.1.0
stacks/nodejs-svelte/1.1.0/devfile.yaml: 2.1.0
stacks/nodejs-svelte/1.2.0/devfile.yaml: 2.2.0

stacks/nodejs-vue/1.0.2/devfile.yaml: 2.1.0
stacks/nodejs-vue/1.1.0/devfile.yaml: 2.1.0
stacks/nodejs-vue/1.2.0/devfile.yaml: 2.2.0

stacks/php-laravel/1.0.1/devfile.yaml: 2.1.0
stacks/php-laravel/2.0.0/devfile.yaml: 2.2.0

stacks/python/2.1.0/devfile.yaml: 2.1.0
stacks/python/3.0.0/devfile.yaml: 2.2.0

stacks/python-django/devfile.yaml: 2.1.0

stacks/udi/devfile.yaml: 2.2.0
```

</details>

So I guess we would need a separate issue for each stack with no version on Devfile 2.2.0, right? Or am I missing anything about the scope of this issue?
- [ ] dotnet50
- [ ] dotnet60
- [ ] dotnetcore31
- [ ] java-maven
- [ ] java-openliberty
- [ ] java-openliberty-gradle
- [ ] java-quarkus
- [ ] java-vertx
- [ ] java-websphereliberty
- [ ] java-websphereliberty-gradle
- [ ] java-wildfly-bootable-jar
- [ ] nodejs
- [ ] python-django

**Comment by rm3l** [comment]
Refinement (Oct 27, 2023):

Scope: only the stacks used by RHTAP
