### ISSUE TITLE
Improve Codecov

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1100]
## Which area/kind this issue is related to?

/area api
/area library
/area registry

## Issue Description
Test coverage across our repos should be improved as most reports show we have less than 50% coverage.  

**Code Coverage**

- [Devfile library](https://app.codecov.io/gh/devfile/library/tree/main)
- [API](https://app.codecov.io/gh/devfile/api/tree/main)
- [Registry Operator](https://app.codecov.io/gh/devfile/registry-operator)
- [Registry -  Index Server](https://app.codecov.io/gh/devfile/registry-support/tree/main/index)

## Acceptance Criteria

- [x] https://github.com/devfile/api/issues/215
- [ ] Improve devfile API testing
- [ ] Improve registry operator testing
- [ ] https://github.com/devfile/api/issues/1192

**Comment by michael-valdron** [comment]
Acceptance criteria needs issues for tracking codecov improvements for each component.

**Comment by Jdubrick** [comment]
Removing stale tag and moving to refinement. It would be good to increase our code coverage for the above repos to ensure functionalities are tested properly.
