### ISSUE TITLE
create a converter in library to convert docker-compose component to outerloop definition

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1121]
/kind user-story

## Which area this user story is related to?

/area library

## User Story

As a developer working on an existing project, I want to be able use the library parser to convert a docker-compose file to a valid devfile outerloop definition that I can use to deploy the application. 

## Acceptance Criteria

- [ ] Existing containers, single service & Multi-service with no dependencies #1122 
- [ ] To be built containers, single service & Multi-service with no dependencies #1123 
- [ ] Multi-service with dependencies within same pod #1124 
- [ ] Multi-service with dependencies in separate pod #1125
