### ISSUE TITLE
Enhance alizer dockerfile port detection logic

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1159]
## Which area this feature is related to?

/area alizer

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

In order to enhance port detection logic, there is a need to improve the logic around the dockerfiles.

**Detailed description:**
An example case where we should had a proper port detection is https://github.com/christianvogt/ocparcade/tree/main/epicpinball. In this case we are able to detect a component in the inner `epicpinball` but we are not able to detect any ports, while the outer `epicpinball` dir has a dockerfile 

## Describe the solution you'd like
A solution could be to detect a dockerfile as a separate component for this cases

## Describe alternatives you've considered
As alizer has many clients maybe this solution could be configurable (it could change according to params we pass to each function

## Additional context
As this issue demands an in-depth solution we might need to add a proposal

Moved from redhat-developer/alizer: https://github.com/redhat-developer/alizer/issues/235

## Related Issues
Child issues for this EPIC:

- [x] https://github.com/devfile/api/issues/1160
- [x] https://github.com/devfile/api/issues/1178
- [x] Add resource to external repo test - https://github.com/devfile-resources/alizer-test-resources/pull/3

**Comment by thepetk** [comment]
Follow the comments of the old issue here: https://github.com/redhat-developer/alizer/issues/235
