### ISSUE TITLE
Alizer's post onboarding actions

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1162]
/kind epic

## Which area/kind this issue is related to?

/area alizer
/area releng
/area test-automation

## Issue Description

After [migrating the Alizer project to Devfiles organization](https://github.com/redhat-developer/alizer/issues/240) we will have to prioritize several issues in order to complete setting up, enhance ci actions and test automation:

- [x] https://github.com/redhat-developer/alizer/issues/40
- [x] https://github.com/redhat-developer/alizer/issues/177
- [x] https://github.com/devfile/api/issues/1163
- [x] https://github.com/devfile/api/issues/1164
- [x] https://github.com/devfile/api/issues/1165
- [x] https://github.com/devfile/api/issues/1166
- [x] https://github.com/devfile/api/issues/1179

**Comment by thepetk** [comment]
The EPIC is completed after the merge of https://github.com/devfile/api/issues/1165
