### ISSUE TITLE
Devfile 2.2.x support for Alizer

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1170]
/kind enhancement 
/kind epic

## Which area this feature is related to?

/area alizer

## Issue details

With the release of devfile 2.2.0, the devfile spec brings a fair amount of new features, such as outerloop and multi version support. With this in mind, it is important to the consumers of alizer to have support for `2.2.x` schema versions.

## Related Issues

UPDATE: @thepetk 
As this is transformed in an EPIC I'm including all children issues here:

- [x] https://github.com/redhat-developer/alizer/issues/225
- [x] https://github.com/devfile/api/issues/1171
- [x] https://github.com/devfile/api/issues/1182

**Comment by thepetk** [comment]
Follow comments from old (pre-migration) issue here: https://github.com/redhat-developer/alizer/issues/159

**Comment by thepetk** [comment]
I've gone through the newly introduced solution for https://github.com/devfile/api/issues/1171 where we have included `--min-version` and `--max-version`. I think two additions could be made here for better user experience:

* As `version` is used both on the `schemaVersion` and the `version` of stack in the devfiles, we might want to make a small rename to the CLI param to `--min-schema-version` and `--max-schema-version`.
* We could include the `versions` list returned from the registry API so we can have a response:
```json
$ ./alizer devfile --min-version 2.2.0 --max-version 2.2.0 ~/github/thepetk/go-ps-script

[
	{
		"Name": "go",
		"Language": "Go",
		"ProjectType": "Go",
		"Tags": [
			"Go"
		],
		"Versions": [
			{
				"SchemaVersion": "2.2.0",
				"Default": false
			},
			{
				"SchemaVersion": "2.2.0",
				"Default": false
			}
		]
	}
]
```

cc @mike-hoang @elsony

**Comment by thepetk** [comment]
Created and added to epic the https://github.com/devfile/api/issues/1182

**Comment by thepetk** [comment]
The last item which is still opened #1172 remains blocked and the EPIC is currently under TODO
