### ISSUE TITLE
Update go projects to v1.19

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1237]
/kind user-story
/kind epic

## Which area this user story is related to?

/area api
/area library
/area registry
/area alizer

## User Story

As a developer of devfile, I want to provide effective patching support the user base of devfile services, so that users continue to devfile services knowing that they have the assurance that these services are receiving the security and bugfix patches when they are needed.

Part of meeting this goal is providing the patches shipped from dependencies of devfile services. With the version of Go used by most of devfile services `1.18` being EOL for some time it is becoming more difficult to provide patches from all the dependencies.

## Acceptance Criteria

- [x] Update Devfile API to use Go 1.19
- [X] Update Devfile Registry Operator to use Go 1.19 (https://github.com/devfile/registry-operator/pull/45)
- [x] #1470
- [x] #1469
- [x] #1473
- [X] Update Alizer to use Go 1.19 (redhat-developer/alizer#182)
- [x] #1249

**Comment by michael-valdron** [comment]
We need to include patching dependencies as one of the tasks to do for each of the acceptance criteria items, to address issues such as #1180.

**Comment by michael-valdron** [comment]
Before starting any child item, we need to ensure consumers of those modules are compatible with Go 1.19 (i.e. using >= 1.19).

**Comment by michael-valdron** [comment]
> Before starting any child item, we need to ensure consumers of those modules are compatible with Go 1.19 (i.e. using >= 1.19).

Some modules may not need this prerequisite, the registry index server for example would not however the devfile library and registry library would need to be compatible with consumer tools and services.

**Comment by thepetk** [comment]
I've added some commits to update the integration-tests repo to go 1.19 here: https://github.com/devfile/integration-tests/pull/99

**Comment by thepetk** [comment]
I'm putting this item for the next refinement call. I think it might be good to refine it and prioritize it at some point.

**Comment by thepetk** [comment]
I've upgraded API to use 1.19 here: https://github.com/devfile/api/pull/1345
cc @michael-valdron

**Comment by michael-valdron** [comment]
Still needs to be done across some of our repositories.

**Comment by thepetk** [comment]
> Still needs to be done across some of our repositories.

+1

**Comment by michael-valdron** [comment]
All maintained Go modules have been updated to Go version 1.19.
