### ISSUE TITLE
Support mySQL service detection

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1264]
/kind user-story
/kind epic

## Which area this user story is related to?

/area alizer

## User Story

As a user of alizer I want to be able to detect if a project is using mysql, so that I can extract important information about its setup or credentials which I might use for deployment etc.

For more information about this topic check the investigation of this EPIC done [here](https://github.com/devfile/api/issues/1213#issuecomment-1731344710).

Every framework/runtime detector should have specific functions and logic to support the detection mysql database services.

## Acceptance Criteria

**DotNet**
- [ ] Add `mysql` detection logic to `DotNetDetector`

**Golang**
- [ ] Add `mysql` detection logic to `BeegoDetector`
- [ ] Add `mysql` detection logic to `EchoDetector`
- [ ] Add `mysql` detection logic to `FastHttpDetector`
- [ ] Add `mysql` detection logic to `GinDetector`
- [ ] Add `mysql` detection logic to `GoDetector`
- [ ] Add `mysql` detection logic to `GoFiberDetector`
- [ ] Add `mysql` detection logic to `MuxDetector`

**Java**
- [ ] Add `mysql` detection logic to `JBossEAPDetector`
- [ ] Add `mysql` detection logic to `MicronautDetector`
- [ ] Add `mysql` detection logic to `OpenLibertyDetector`
- [ ] Add `mysql` detection logic to `QuarkusDetector`
- [ ] Add `mysql` detection logic to `SpringDetector`
- [ ] Add `mysql` detection logic to `VertxDetector`
- [ ] Add `mysql` detection logic to `WildflyDetector`

**Javascript**
- [ ] Add `mysql` detection logic to `NodejsDetector`

**PHP**
- [ ] Add `mysql` detection logic to `LaravelDetector`

**Python**
- [ ] Add `mysql` detection logic to `DjangoDetector`
- [ ] Add `mysql` detection logic to `FlaskDetector`
