### ISSUE TITLE
Implement changes to sync registry operator and registry helm chart - Part 1

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1274]
/kind user-story
/kind epic

## Which area this user story is related to?

/area registry

## User Story

As a registry admin, I want the deployment methods to be synced, so that I can choose my method of devfile registry deployment with out worrying about differences in my deployments.

The setup for the [devfile registry helm chart](https://github.com/devfile/registry-support/tree/main/deploy/chart/devfile-registry) and [devfile registry operator](https://github.com/devfile/registry-operator) are currently inconsistent. We need to ensure that the registry helm chart and registry operator setups are in sync before we can provide official releases.

After investigating what sync changes we need #1193, we need to implement them to meet this objective.

## Acceptance Criteria

- [x] https://github.com/devfile/api/issues/1428
- [x] https://github.com/devfile/api/issues/1430
- [x] https://github.com/devfile/api/issues/1431
- [x] https://github.com/devfile/api/issues/1432
- [x] https://github.com/devfile/api/issues/1433
- [x] https://github.com/devfile/api/issues/1434
- [x] https://github.com/devfile/api/issues/1436
- [x] https://github.com/devfile/api/issues/1438
- [x] https://github.com/devfile/api/issues/1439
- [x] https://github.com/devfile/api/issues/1441

**Comment by michael-valdron** [comment]
Cannot be refined and sized until the conclusion of #1193.

**Comment by maysunfaisal** [comment]
https://github.com/devfile/api/issues/1193 is the Spike investigation for this issue

**Comment by michael-valdron** [comment]
/kind epic

> https://github.com/devfile/api/issues/1193#issuecomment-1918329792

Due to scope of the findings in #1193 this issue will be converted into an epic and acceptance criteria broken down into different child issues.

**Comment by michael-valdron** [comment]
Final issue has been resolved https://github.com/devfile/api/issues/1441, closing this epic now..
