### ISSUE TITLE
Review and update contributing guides

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1281]
## Which area/kind this issue is related to?

/kind epic

## Issue Description

Contributing guides in our repositories should be review and updated with the up to date information. Additionally, an investigation should be done to determine if a portion of the contributing guides should be centralized under [devfile/api](https://github.com/devfile/api/blob/main/CONTRIBUTING.md).

**Contributing Guides**
- [devfile/api](https://github.com/devfile/api/blob/main/CONTRIBUTING.md)
- [devfile/registry](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md)
- [devfile/registry-support](https://github.com/devfile/registry-support/blob/main/CONTRIBUTING.md)
- [devfile/registry-operator](https://github.com/devfile/registry-operator/blob/main/CONTRIBUTING.md)
- [devfile/devfile-web](https://github.com/devfile/devfile-web/blob/main/CONTRIBUTING.md)
- [devfile/alizer](https://github.com/devfile/alizer/blob/main/CONTRIBUTING.md)
- [devfile/library](https://github.com/devfile/library/blob/main/CONTRIBUTING.md)

## Acceptance Criteria

- [x] https://github.com/devfile/api/issues/1353
- [x] https://github.com/devfile/api/issues/1346
- [x] https://github.com/devfile/api/issues/1347
- [x] https://github.com/devfile/api/issues/1348
- [x] https://github.com/devfile/api/issues/1349
- [x] https://github.com/devfile/api/issues/1350
- [x] https://github.com/devfile/api/issues/1351
- [x] https://github.com/devfile/api/issues/1352

**Comment by michael-valdron** [comment]
/kind epic

Due to the size of the child stories and criteria this issue should be an epic.

**Comment by michael-valdron** [comment]
Removing contributor assignments as part of the acceptance criteria for this issue in favour of splitting issues ad hoc if a contributor does not feel comfortable working on all acceptance criteria in an assigned issue.

**Comment by michael-valdron** [comment]
Added to Q2 goals.

**Comment by michael-valdron** [comment]
Final contributing guide revision changes is in review: https://github.com/devfile/api/pull/1597

**Comment by michael-valdron** [comment]
All contributing guides have been updated, continuing to track the creation of the upcoming contributing guide template document under #1591.
