### ISSUE TITLE
CNCF Security Slam Initiative

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1299]
/kind epic
## Which area this user story is related to?

/area api
/area library
/area registry
/area alizer
/area devworkspace
/area landing-page

## EPIC

CNCF is having a Security Slam initiative where they are running a month long event where the CNCF projects are cleaned, maintained and processes improved for Security among other reasons. This translates to a score on the CLO Monitor https://clomonitor.io/projects/cncf/devfile

The full discussion can be found at https://github.com/devfile/api/discussions/1283

## User Stories

The Spike user story https://github.com/devfile/api/issues/1292 estimated the work to be done for each badge and the following stories have more information about them:

- [x] https://github.com/devfile/api/issues/1296
- [ ] https://github.com/devfile/api/issues/1297
- [x] https://github.com/devfile/api/issues/1298

We also need to determine what other devfile repositories need to be added to the CLO Monitor report:

- [x] https://github.com/devfile/api/issues/1371
