### ISSUE TITLE
Add alizer support for Ruby & Ruby on Rails projects

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1325]
## Which area this feature is related to?

/area alizer

## Which functionality do you think we should add?

As a developer I'd like to be able to detect ruby based projects being enriched with the rails framework and detect any ports that might have been set inside the source code.

More information about Ruby: https://www.ruby-lang.org/en/
More information about Ruby on Rails: https://rubyonrails.org/

**Why is this needed? Is your feature request related to a problem?**

Ruby is one of the most popular programming languages and as a result many web applications are based on this language. On the other hand, Ruby on Rails is one of the main frameworks used for this language.

## Describe the solution you'd like

* A new enricher should be created for the `ruby` language called `ruby_enricher`.
* A new detector should be created for the `rails` framework called `rails_detector`.
* The `language-customization.yaml` should be updated to reflect that the ruby language will now have detected components.
* Regarding port detection more information on how the rails framework sets its running port can be found here: https://guides.rubyonrails.org/configuring.html

## Acceptance Criteria

- [ ] #1397
- [ ] Component detection support for `ruby` and `ruby on rails` has been added.
- [ ] We are able to detect ports for `ruby on rails` components.
- [ ] Update to the documentation (component & ports detection) has been made.
- [ ] New test cases have been added.

**Comment by michael-valdron** [comment]
Converting to epic

**Comment by thepetk** [comment]
updated the description and created https://github.com/devfile/api/issues/1397 as a spike item :)

cc @michael-valdron
