### ISSUE TITLE
REST API `lastModified` query parameter for requesting filtered index schemas

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1327]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

Allows a consumer of the REST API to request for filtered down responses when working with `GET /index` and `GET /v2index`.

**Detailed description:**

Currently for `GET /index` and `GET /v2index`, there are a few query parameters which provide filtering based on schema version and architecture type. It would be good to have a new `lastModified` filter.

Related issue: #959

## Describe the solution you'd like

**Tasks**
- [ ] Stack/Sample `lastModified` named query parameter
- [ ] Additional testing additions to account for changes done
- [ ] Additional documentation additions to REST API docs to describe these parameters

## Describe alternatives you've considered

Without these changes, the filters in this issue would need to be applied on the client side which both requires the registry index server to create the entire list of index schemas to send as the response and put additional load on the consumer having to filter and pull out needed information after the fact.

**Comment by michael-valdron** [comment]
Sizing this issue as **3 days** from the days taken away from #959's sizing: https://github.com/devfile/api/issues/959#issuecomment-1793038352

**Comment by thepetk** [comment]
Removing the `stale` label as the issue is brought inside sprint

**Comment by Jdubrick** [comment]
Currently have it setup to grab the dates a file was last modified through `git log` as part of the build scripts. We should be able to take those dates and update the modified date of each devfile so the index can reference that and use it for that endpoint
