### ISSUE TITLE
Create Ruby on Rails stack entry for community devfile registry

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1412]
## Which area/kind this issue is related to?

/kind task

/area registry

## Issue Description

The creation of a Ruby on Rails devfile stack to show up on the community devfile registry (https://registry.devfile.io).

## Acceptance Criteria

- [ ] Add the icon picked in devfile/api#1413 to the [devfile-samples/devfile-stack-icons](https://github.com/devfile-samples/devfile-stack-icons) repository and use filename `<name-of-stack>.svg`, e.g. `ruby-on-rails.svg`
- [ ] Add stack entry to [registry/stacks](https://github.com/devfile/registry/tree/964572299468c33030323a79fcc43d3a3d00e8c5/stacks) that follows the stack layout (e.g. [go stack](https://github.com/devfile/registry/tree/964572299468c33030323a79fcc43d3a3d00e8c5/stacks/go)):
   - A stack directory with the stack name
   - `stack.yaml` with the general stack information and initial stack version in the stack directory
   - An initial stack version subdirectory containing the stack devfile and any supporting resource directories
- [ ] Setup stack devfile with both [innerloop](https://devfile.io/docs/2.2.2/innerloop-vs-outerloop#what-is-innerloop) and [outerloop](https://devfile.io/docs/2.2.2/innerloop-vs-outerloop#what-is-outerloop) build and deployment setups based on findings in devfile/api#1413
- [ ] Add stack metadata to devfile
- [ ] Include Ruby on Rails starter project (devfile/api#1411) in devfile
- [ ] Create OWNERS file and include stack owner(s)
- [ ] Update any related documentation
