### ISSUE TITLE
Implement changes to sync registry operator and registry helm chart - Part 2

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1446]
/kind user-story
/kind epic

## Which area this user story is related to?

/area registry

## User Story

As a registry admin, I want the deployment methods to be synced, so that I can choose my method of devfile registry deployment with out worrying about differences in my deployments.

The setup for the [devfile registry helm chart](https://github.com/devfile/registry-support/tree/main/deploy/chart/devfile-registry) and [devfile registry operator](https://github.com/devfile/registry-operator) are currently inconsistent. We need to ensure that the registry helm chart and registry operator setups are in sync before we can provide official releases.

Part 2 to #1274 

## Acceptance Criteria

- [ ] https://github.com/devfile/api/issues/1429
- [x] https://github.com/devfile/api/issues/1435
- [x] https://github.com/devfile/api/issues/1440
- [x] https://github.com/devfile/api/issues/1437
- [x] https://github.com/devfile/api/issues/1442
- [ ] Use consistent image fields between helm chart and registry operator
- [x] https://github.com/devfile/api/issues/1443
- [x] https://github.com/devfile/api/issues/1444
