### ISSUE TITLE
Mirror internal devfile registry issues for devfile project tracking

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1485]
## Which area/kind this issue is related to?

/area ci

## Issue Description

The internal devfile registry JIRA issue tracking project [DEVREG](https://issues.redhat.com/projects/DEVREG) hosts a number of issues regarding our devfile registry deployments, security vulnerabilities, and sometimes devfile team specific issues. Since we primarily track our [project](https://github.com/orgs/devfile/projects/10) and [issues](https://github.com/devfile/api/issues) on GitHub we should have a reference within our GitHub tracking to our JIRA issues.

The idea here is to mirror the internal issues on our GitHub issue tracking and only provide overview and non-sensitive information (**this may vary depending on security-level**) about them with a reference link to the source JIRA issue. This way we can still track these issues within our [devfile project](https://github.com/orgs/devfile/projects/10) without exposing them.

## Acceptance Criteria

- [ ] Completion of https://github.com/devfile/api/issues/1269 for use of @devfile-robot GitHub account
- [ ] Investigate what information should be kept separated, GitHub issue versus JIRA issue
- [ ] Investigate which overview information we should mirror and any changes in what is mirror based on security level
- [ ] Mirror automation using JIRA robot account via PAT to read overview information of [DEVREG JIRA issues](https://issues.redhat.com/projects/DEVREG) (i.e. titles and links)
- [ ] Mirror automation using @devfile-robot account via PAT to creates mirrored [devfile/api issues](https://github.com/devfile/api/issues) that points back to their tied [DEVREG JIRA issues](https://issues.redhat.com/projects/DEVREG)
  - **Optional**: Since most issues from [DEVREG](https://issues.redhat.com/projects/DEVREG) are registry related, give `area/registry` to these issues by default. Authors can alter this in specific scenarios.
- [ ] Retire sprint board for [DEVREG](https://issues.redhat.com/projects/DEVREG)

**Comment by michael-valdron** [comment]
Closing in favour of mirroring DEVREG issues manually with supporting slack alerting #1486.
