### ISSUE TITLE
Support testing schema versions 2.2.2 & 2.2.1 upon registry CI checks

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1494]
## Which area this feature is related to?

/kind epic

### Which area this bug is related to?

/area library
/area registry

## Issue Descripton

The registry tests with `odo3` are failing due to old library version

More detailed, the `check_odov3` check is failing because `odo` is currently using an old version of the `devfile/library` which does not support atm the `2.2.1` and `2.2.2`. In order to reproduce this behavior someone should Install `odo` version `3.15.0` and try to run `odo dev` using a devfile having `schemaVersion=2.2.1`.

In order to have more thorough testing for the registry stack updates our CI checks should allow testing those versions. Note that as a temporary fix the `2.2.1` & `2.2.2` versions [have been excluded from the tests](https://github.com/devfile/registry/pull/356).

## Acceptance Criteria
- [x] https://github.com/devfile/api/issues/1477
- [x] https://github.com/devfile/api/issues/1479
- [x] We should open a PR to https://github.com/redhat-developer/odo updating the `github.com/devfile/library/v2` dependency.
- [x] https://github.com/devfile/api/issues/1415

**Comment by Jdubrick** [comment]
Once this is completed we will need to undo the patch here: https://github.com/devfile/registry/pull/356

**Comment by thepetk** [comment]
Re-opening as the PR merged was a temporary solution

**Comment by thepetk** [comment]
FYI after the temporary fix, I've transformed this issue into an EPIC

**Comment by thepetk** [comment]
[PR](github.com/redhat-developer/odo/pull/7240) is now merged

**Comment by thepetk** [comment]
Closing as all items are completed
