### ISSUE TITLE
Devfile 2.0.0 proposal

### ISSUE THREAD

**Issue by l0rd** [devfile/api#15]
## Devfile 2.0.0 ([milestone](https://github.com/devfile/kubernetes-api/milestone/1))

Here is a list of proposals to include in the next version of the `Devfile` format. Proposals need to be reviewed and approved. We are flagging issues with 👍once they have been reviewed and approved.

### 1. Repositories Setup

We would like to split `Devfile` related source code in 2 distinct repositories:

#### [che-incubator/devworkspace-api](https://github.com/che-incubator/devworkspace-api)

The `Devfile` schema is directly generated from the `DevWorkspace` API. PRs to change the `Devfile` format spec (documentation included) should be done here. Issues related to the format should be also created here.

#### [redhat-developer/devfile](https://github.com/redhat-developer/devfile)

The `Devfile` specification doc and examples are published here. Only PRs to add new examples should be done here.

Subtasks related to the repositories setup:
- [x] Move [devfile repository](https://github.com/redhat-developer/devfile) to the devfile organisation 👍
- [x] Move [devworkspace-api](https://github.com/che-incubator/devworkspace-api) repository to the devfile organisation 👍
- [ ] [Setup a GH action to generate and publish the Devfile OpenAPI schema](https://github.com/che-incubator/devworkspace-api/issues/11) 👍
- [x] [Setup a GH action to generate and publish the Devfile Spec Documentation](https://github.com/che-incubator/devworkspace-api/issues/12) 👍

### 2. Changes for ODO

- [x] [Specify the source mapping path (CHE_PROJECT_ROOT) for component containers](https://github.com/che-incubator/devworkspace-api/issues/17) 👍
- [x] [Id and label for Composite commands](https://github.com/che-incubator/devworkspace-api/issues/18) 👍
- [x] [Specify size of volume for component](https://github.com/che-incubator/devworkspace-api/issues/14) 👍
- [x] [Allow volumes to be shared across components](https://github.com/che-incubator/devworkspace-api/issues/19) 👍
- [x] ~~[On startup, automatically copy files/directories from the Git location of a dev file, to a container](https://github.com/che-incubator/devworkspace-api/issues/20)~~  superseded by #32
- [x] [Environment variables for a specific command](https://github.com/che-incubator/devworkspace-api/issues/21) 👍
- [x] [Renaming workdir into workingDir](https://github.com/che-incubator/devworkspace-api/issues/22) 👍
- [x] [Commands group (application lifecycle)](https://github.com/che-incubator/devworkspace-api/issues/27) 👍
- [x] [Out of main pod containers](https://github.com/devfile/kubernetes-api/issues/48) 👍
- [ ] [Stacks/Devfile matching rules](https://github.com/devfile/kubernetes-api/issues/40) 👍
- [ ] [Devfile metadata: add a link to an external website](https://github.com/devfile/kubernetes-api/issues/38) 👍
- [x] [starterProjects and projects description](https://github.com/devfile/kubernetes-api/issues/42)

### 3. Changes for Che / Codewind

- [x] [Polymorphic component type UX in a Devfile](https://github.com/che-incubator/devworkspace-api/issues/4) 👍
- [x] [Renaming dockerimage component type](https://github.com/che-incubator/devworkspace-api/issues/8) 👍
- [x] [Devfile should have a `schemaVersion` attribute](https://github.com/che-incubator/devworkspace-api/issues/7) 👍
- [x] [The Devfile schema/samples should have optional version and name attributes](https://github.com/che-incubator/devworkspace-api/issues/10) 👍
- [x] [Names mandatory for k8s/openshift/container but not for plugins](https://github.com/che-incubator/devworkspace-api/issues/9) 👍 
- [x] [Add lifecycle bindings to bind commands to specific events](https://github.com/che-incubator/devworkspace-api/issues/32)👍 
- [x] [Better plugin mechanism ](https://github.com/che-incubator/devworkspace-api/issues/31) 👍 
- [x] [Containers endpoints (routes/ingresses)](https://github.com/che-incubator/devworkspace-api/issues/33) 👍 
- [x] [Find a better naming for chePlugin spec reference](https://github.com/che-incubator/devworkspace-api/issues/13) 👍
- [x] [New type of command to `apply` a component](https://github.com/devfile/kubernetes-api/issues/56) 👍
- [ ] [Run exec commands as specified user](https://github.com/devfile/kubernetes-api/issues/34) 👍

### 4. Changes to support Stacks definition

- [ ] [Parent devfiles](https://github.com/che-incubator/devworkspace-api/issues/25) 👍

**Comment by slemeur** [comment]
There should be a backward compatibility mechanism between devfile 1.x and devfile 2.0. We've discussed about it and that seems still valuable to Che adopters (and downstream products).

**Comment by l0rd** [comment]
v2.0 has been released
