### ISSUE TITLE
Implement Multi Arch Support For Devfile Repositories

### ISSUE THREAD

**Issue by Jdubrick** [devfile/api#1608]
/kind epic
/area ci
/area registry

# Epic Goal

In order to make a smooth transition to running our CI workloads on arm64 nodes we need to ensure that our images can be built for arm64 architectures as well as amd64.

This issue is related to https://github.com/devfile/api/issues/1492

# Acceptance Criteria

- [x]  https://github.com/devfile/api/issues/1537
- [x] https://github.com/devfile/api/issues/1546
- [x] https://github.com/devfile/api/issues/1547
- [x] https://github.com/devfile/api/issues/1548
- [x] https://github.com/devfile/api/issues/1549
- [x] https://github.com/devfile/api/issues/1550
- [x] https://github.com/devfile/api/issues/1551
