### ISSUE TITLE
Define a public common devfile registry that can be shared across different tools

### ISSUE THREAD

**Issue by elsony** [devfile/api#225]
Define a public common devfile registry that can be shared across different tools. The content of the devfile registry is based on the GitHub content under https://github.com/devfile/registry

This item includes:
- [x] Build and package the devfile registry content to build the devfile registry image and the devfile index image
    1) Create a tagged release of https://github.com/devfile/registry and push the resultant devfile index image to `quay.io/devfile/devfile-index`
- [x] Work with the AppSRE team to deploy the devfile registry to a publicly available cluster and address any issues they raise
   - [x] Expose a metrics endpoint in both registry containers https://github.com/devfile/api/issues/283
   - [x] Move the registry containers to UBI and to quay.io, as needed. https://github.com/devfile/api/issues/294
   - [x] Create OpenShift template for deploying the hosted registry https://github.com/devfile/registry-support/pull/24
   - [x] Expose a metric to measure the end-end latency of requests to the index server https://github.com/devfile/api/issues/336. PR: https://github.com/devfile/registry-support/pull/27

This item is part of #82

**Comment by johnmcollier** [comment]
Blocked by https://github.com/devfile/api/issues/190 and https://github.com/devfile/api/issues/226

**Comment by johnmcollier** [comment]
Added subpoints for the two tasks for this item outlining what needs to be done.

**Comment by johnmcollier** [comment]
PR that adds an OpenShift template to Github: https://github.com/devfile/registry-support/pull/24

**Comment by johnmcollier** [comment]
Gonna close this one out now. We've got the registry successfully deployed and running on registry.devfile.io

I've opened up https://github.com/devfile/api/issues/376 for the pre-transition period steps for the registry

**Comment by elsony** [comment]
This item is done
