### ISSUE TITLE
Library api improvements

### ISSUE THREAD

**Issue by mmulholla** [devfile/api#306]
My comments after doing a quick review of the api's

- [x] ~Add, Update Set api's should parse what is provided to make sure it is valid, return an error if not.~ we do not help validate, only do simple add/update/delete
- [x] ~Update api's should return an error if the updated object is not already known to the parser~ https://github.com/devfile/api/issues/448
- [x] Add api's tend to return on first error, rather than process everything provided. For example if I add 5 components 4 will be added if the 5th is a duplicate but only 1 will be added if the 2nd is a duplicate.  https://github.com/devfile/api/issues/449
- [x] No Delete api's except for Volumes. Delete api's would be useful. #357 
- [ ] Why Volumes api's but nothing for Groups, Endpoints etc? (Maysun: Not sure the purpose of an util for Command Groups. Dont think we will add util funcs for Endpoint until a need arises, users can use UpdateComponent)
- [x] ~Why utils GetDevfileContainerComponents, and GetDevfileVolumeComponents - planning to expand these to be comprehensive for command, projects etc?~ Deprecated, they are now available via https://github.com/devfile/library/blob/master/pkg/devfile/parser/data/v2/common/options.go
- [x] Difficult to find methods for creating and managing a devfile (Maysun: we already have a writer func `func (d *DevfileObj) WriteYamlDevfile() error`. ) (Added writer usage example in library readme https://github.com/devfile/library/commit/6c950fec9d919248f2e6735c7a53ed55e102ba17#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
- [x] ~Inconstant parameters required~ already fixed

Also we need api documentation which provides a list of errors returned.

**Comment by dharmit** [comment]
> No Delete api's except for Volumes. Delete api's would be useful.

+1. 

We are looking for `DeleteComponent` to be able to delete a component from the devfile. The use case for odo is to delete a Kubernetes inlined component from devfile when the user does `odo service delete`. It's already possible to add a Kubernetes inlined component when doing `odo service create` since `AddComponent` method already exists.

odo issue dependent on this is https://github.com/openshift/odo/issues/4160.

**Comment by yangcao77** [comment]
Closing this issue since it has been completed.
