### ISSUE TITLE
Devfile registry air gap/offline installation

### ISSUE THREAD

**Issue by elsony** [devfile/api#329]
A devfile refers to various resources, e.g. container images, projects, and starter projects. The current devfile registry currently does not store those supporting resources as part of the registry. This means that the user will need to have access to those resources when using those devfiles. This item adds support to install a devfile registry in an air-gapped environment.

Design doc: https://docs.google.com/document/d/15PpUGiWOXjfQ5GtJFPHp0cG73jtpmw1H9AkCrnJVD2E/edit?usp=sharing

Acceptance criteria:

1. Implement according to the design on the design doc so that the offline installation is self-contained and can be installed without internet access
2. Testing to verify the implementation according to the design doc
3. Document on how to do air gap installation

**Related Issues**
Child issues for this EPIC:

- [x]  https://github.com/devfile/api/issues/1203
- [x]  https://github.com/devfile/api/issues/1220
- [x]  https://github.com/devfile/registry/pull/197
- [x]  https://github.com/devfile/api/issues/1222

**Comment by rkratky** [comment]
Docs JIRA issue: https://issues.redhat.com/browse/RHDEVDOCS-2872

**Comment by nickboldt** [comment]
Support for offline/airgap is a vital requirement for getting any of this new registry stuff into CRW, as CRW registry builds are by default offline so they can be used behind an airgap/proxy. 

Please don't forget about this requirement when designing how to build your registries.

**Comment by michael-valdron** [comment]
Adding this to triage as there seems to be criteria still being worked out.

cc: @elsony

**Comment by elsony** [comment]
> We should also review how the devfile library can access offline parent resources from the registry, especially since a git clone is being done

It is already documented in the design doc. See section 1 i.

**Comment by elsony** [comment]
> Adding this to triage as there seems to be criteria still being worked out.

Added acceptance criteria

**Comment by mike-hoang** [comment]
https://github.com/devfile/api/issues/1203 - merged which now allows starter projects to be downloaded and the devfiles updated to use the offline starter projects

https://github.com/devfile/api/issues/1220 - will take into consideration all the uri paths and download them to the stack directory

https://github.com/devfile/registry/pull/197 - entry point for creating the offline registry image and will be merged after all the child tasks are completed
