### ISSUE TITLE
Devfile public community registry goes live

### ISSUE THREAD

**Issue by elsony** [devfile/api#372]
Tracking work remaining work before devfile public community registry goes live (announcement):
P1:
- [x] odo to move to the new registry (create PR on odo repo) (https://github.com/devfile/api/issues/367)
- [x] Pre-transition period steps for the hosted devfile registry service (https://github.com/devfile/api/issues/376)
- [x] Stack creator switch over (https://github.com/devfile/api/issues/391)
- [x] Stability monitoring after odo PR merge (check if any of their PR tests hitting the live server)
- [x] Registry update (starts with once per week) (https://github.com/devfile/api/issues/390)
- [x] QE tests
- [x] Odo integration tests should use staging devfile registry (registry.stage.devfile.io) (https://github.com/openshift/odo/issues/4639)

P2:
- [x] Stack addition/update request process (https://github.com/devfile/api/issues/390)
- [ ] Documentation for stack requirement
- [ ] Blog post on public registry (#408)
- [ ] Stack issue tracking
- [x] odo plan to GA with the new registry
- [x] Odo URL migration (odo doc to clean existing preference)
- [ ] Add devfile registry operator to OperatorHub (https://github.com/devfile/api/issues/410)

**Comment by elsony** [comment]
Closing this one off since public community went live. Any new work will be tracked by new issues.

**Comment by elsony** [comment]
Closing old item since the devfile community registry went live for a while already.
