### ISSUE TITLE
Put devfile registry operator to OperatorHub

### ISSUE THREAD

**Issue by elsony** [devfile/api#410]
/kind user-story
/kind epic

## Which area this user story is related to?

/area registry
/area releng

## User Story

As a developer working on the integration of the devfile registry service in another project, I want to have the devfile registry operator available on the OperatorHub, so that I can receive stable releases of the registry operator from an official source for my projects devfile registry deployments.

Before we can make the operator available in the catalog, we will need to stabilize it first. We made some major changes in the last few months to migrate the operator to newer k8s dependencies and re-worked the way the registry viewer gets deployed but it's caused some issues that we are still working through. Once things are stabilize, we will need to ensure we have processes and test coverage to ensure we can update on a regular basis.

These are some of the considerations that will apply to both artifacthub and operatorhub:

1. We will need to come up with a release process. Currently one does not exist but once we cut one, we will consider releasing on a regular cadence TBD (either per quarter and/or driven by dependency updates whichever comes first). Our plan is to support openshift 4.12+ in our first release

2. We need to ensure there's additional testing before publishing to the catalogs. e.g. we do not have tests for the OLM bundles and we don't have integration tests with openshift. We will probably need to add tests for Eclipse Che since they are another client that is interested in using the operator

3. Ensure helm chart and operator are consistent. Currently they are out of sync

**Issue revised by: @michael-valdron**
**Originally defined: https://github.com/devfile/api/issues/1007#issuecomment-1494553859 by @kim-tsao**

## Acceptance Criteria

- [x] https://github.com/devfile/api/issues/1028
- [x] https://github.com/devfile/api/issues/1106
- [x] https://github.com/devfile/api/issues/1211
- [x] https://github.com/devfile/api/issues/1301
- [x] https://github.com/devfile/api/issues/1015
- [x] https://github.com/devfile/api/issues/1267
- [x] https://github.com/devfile/api/issues/1194
- [x] https://github.com/devfile/api/issues/1233
- [x] https://github.com/devfile/api/issues/1251

**Removed Criteria**
- [x] ~https://github.com/devfile/api/issues/1193~
- [x] ~https://github.com/devfile/api/issues/1195~
- [x] ~Add testing for registry operator OLM bundles~

**Comment by michael-valdron** [comment]
https://github.com/devfile/api/issues/1106 has been started therefore moving into in progress.

**Comment by ibuziuk** [comment]
@michael-valdron thanks for the update, any news on the operator availability on OperatorHub? is it still planned to be published by the end of August?

**Comment by michael-valdron** [comment]
> @michael-valdron thanks for the update, any news on the operator availability on OperatorHub? is it still planned to be published by the end of August?

@ibuziuk This is still planned for the end of August. Currently finishing up final changes for operator sdk setup sync and manifest updates #1106 a prerequisite for the pre-release of registry operator on OperatorHub #1211, for #1211 I'll need to open a PR to https://github.com/k8s-operatorhub/community-operators for review and operator submission, I expect most of the process I will be going through next week is the review process.

**Comment by michael-valdron** [comment]
Hi @ibuziuk,

Due to some issues we are experiencing with OpenShift CI while getting the release changes in we will have to push the target date for the pre-release of the OperatorHub publication until next week.

I apologize for the inconvenience.

**Comment by michael-valdron** [comment]
> Due to some issues we are experiencing with OpenShift CI while getting the release changes in we will have to push the target date for the pre-release of the OperatorHub publication until next week.

https://github.com/devfile/api/issues/1106#issuecomment-1699848699

**Comment by michael-valdron** [comment]
The prerequisite #1106 for the pre-release is completed. The pre-release #1211 will include the following changes from this epic:
- #1106 
- #1015 
- #1233

**Comment by ibuziuk** [comment]
@michael-valdron thanks for following up on OperatorHub availability. Am I correct that the operator is going to be community-supported? any plans for having a Red Hat supported offering?

**Comment by michael-valdron** [comment]
> @michael-valdron thanks for following up on OperatorHub availability. Am I correct that the operator is going to be community-supported? any plans for having a Red Hat supported offering?

@ibuziuk That is correct, the devfile registry operator will be community-supported. At this time, we don't currently have plans for a separate Red Hat offering but we are still supporting OpenShift deployment compatibility, OCP 4.12 at the time of writing.

**Comment by michael-valdron** [comment]
> The prerequisite #1106 for the pre-release is completed. The pre-release #1211 will include the following changes from this epic:
> 
>     * [Registry operator should be in sync with operator SDK releases #1106](https://github.com/devfile/api/issues/1106)
> 
>     * [Complete documentation coverage of registry operator #1015](https://github.com/devfile/api/issues/1015)
> 
>     * [Update CONTRIBUTING for registry operator #1233](https://github.com/devfile/api/issues/1233)

Recent set backs with #1211, changes I feel we still need for official release, and #1211 meeting the general objective or MVO of #410 (publishing to OperatorHub) we'll be using this as the closing issue along with #1194 to the epic. All remaining open issues excluding these two will be included in the release mentioned for #1211.

The following items are to be removed from this epic and moved into a following epic which will be tied to an official release:
- https://github.com/devfile/api/issues/1193
- https://github.com/devfile/api/issues/1195
- (not a created issue yet) Add [workflow for] testing for registry operator OLM bundles

**Comment by michael-valdron** [comment]
Review of the publication to OperatorHub.io has begun with passing tests: https://github.com/k8s-operatorhub/community-operators/pull/3287

Full tracking of this posted to https://github.com/devfile/api/issues/1211.

**Comment by michael-valdron** [comment]
> https://github.com/devfile/api/issues/1211#issuecomment-1764454183

As mentioned under the linked comment, the registry operator `v0.1.3` is now published on OperatorHub.io: https://operatorhub.io/operator/registry-operator

**Comment by michael-valdron** [comment]
CI process for publishing release images #1267 is needed to complete the release process #1194.

**Comment by ibuziuk** [comment]
folks, looks like the operator in not available on OpenShift (at least on 4.13.17)
<img width="1166" alt="Screenshot 2023-10-23 at 15 11 41" src="https://github.com/devfile/api/assets/1461122/0da3044d-8050-4947-ad81-af82e8d65d89">

Could you please make it available there by default.

**Comment by michael-valdron** [comment]
> folks, looks like the operator in not available on OpenShift (at least on 4.13.17) <img alt="Screenshot 2023-10-23 at 15 11 41" width="1166" src="https://user-images.githubusercontent.com/1461122/277347601-0da3044d-8050-4947-ad81-af82e8d65d89.png">
> 
> Could you please make it available there by default.

OperatorHub.io and OperatorHub for OpenShift are under two different repositories:
- https://github.com/k8s-operatorhub/community-operators is for OperatorHub.io
- https://github.com/redhat-openshift-ecosystem/community-operators-prod is for the OpenShift community catalog
    - https://docs.openshift.com/container-platform/4.13/operators/understanding/olm-rh-catalogs.html

I'll open an issue to mirror our publication under that catalog as well.

**Comment by michael-valdron** [comment]
> > folks, looks like the operator in not available on OpenShift (at least on 4.13.17) <img alt="Screenshot 2023-10-23 at 15 11 41" width="1166" src="https://user-images.githubusercontent.com/1461122/277347601-0da3044d-8050-4947-ad81-af82e8d65d89.png">
> > Could you please make it available there by default.
> 
> OperatorHub.io and OperatorHub for OpenShift are under two different repositories:
> 
>     * https://github.com/k8s-operatorhub/community-operators is for OperatorHub.io
> 
>     * https://github.com/redhat-openshift-ecosystem/community-operators-prod is for the OpenShift community catalog
>       
>       * https://docs.openshift.com/container-platform/4.13/operators/understanding/olm-rh-catalogs.html
> 
> 
> I'll open an issue to mirror our publication under that catalog as well.

Created #1301

**Comment by michael-valdron** [comment]
All items have been completed, will be closing with the completion of the demo for https://github.com/devfile/api/issues/1194.

**Comment by michael-valdron** [comment]
> All items have been completed, will be closing with the completion of the demo for #1194.

Demo for #1194 is completed which brings this epic to a close.
