### ISSUE TITLE
Devfile - CNCF proposal along with devworkspace

### ISSUE THREAD

**Issue by rtaniwa** [devfile/api#426]
**Problem**
We would like the devfile to be spreading accross different CNCF tools. There are different initiatives that are already existing: Tilt.dev, garden.io and not to mention things from gitpod or codespaces. 

**Goal**
Unifying over a community effort on a commun definition of developer environment would be critical.

**Why is it important?**
Increase reach and community awarness/engagement on devfile.

**Subtasks**
- [x] Update devfile org projects from EPL to Apache license @l0rd 
- [x] Introduce the devfile at Kubernetes [sig-apps](https://github.com/kubernetes/community/tree/master/sig-apps) bi weekly call (14th of June) @l0rd 
- [ ] Required tasks to fill [the proposal form](https://docs.google.com/document/d/1IlhqnmhSzs3aTPMkp_75JPYz6LD21aK1sNPrBNruDt0/edit) ([use this google doc for review](https://docs.google.com/document/d/1nIJRuxTBGQ2u26bnReTnVHaWH_uvHQvVCK0gS649_80/edit#)):
  - [x] A link to project on GitHub (https://github.com/devfile/api)
  - [x] A short description of alignment to cloud native
  - [x] Comparison with similar projects
  - [x] A link to the project public roadmap
  - [ ] A link to the project contribution guidelines
  - [x] A link to the project Code of Conduct
- [ ] Optional tasks
  - [x] A link to a website
    - [x] devfile landing page cncf/toc#379 (https://docs.devfile.io/landing-page/)
    - [ ] devworkspace landing page
  - [ ] A link to a pre-existing presentation (slides / video)
  - [ ] A statement on alignment with existing CNCF projects
  - [x] New devfile logo @rtaniwa (https://github.com/devfile/api/tree/main/docs/icons)
  - [ ] A blog post (co-signed by participating companies)
- [ ] Tasks required by the [sandbox onboarding process](https://github.com/cncf/sandbox/issues/179):
  - [x] Review docs: [project proposal process](https://github.com/cncf/toc/blob/main/process/project_proposals.adoc#introduction), [services for CNCF projects](https://www.cncf.io/services-for-projects/), [CNCF IP policy](https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy), [LF trademark guidelines](https://www.linuxfoundation.org/en/trademark-usage/), [3rd party licenses allow list](https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist) - Ida, JetBrains, @l0rd
  - [x] Adopt an [open governance](https://contribute.cncf.io/maintainers/governance/): [GOVERNANCE.md template](https://github.com/cncf/project-template/blob/main/GOVERNANCE-maintainer.md) @l0rd ([PR](https://github.com/devfile/api/pull/746)) 
    - [x] Create a mailing list: the template requires it - @l0rd (we will use GitHub discussions)
  - [x] PR to be added to the CNCF landscape - @l0rd
  - [x] Add project to [CNCF contribute](https://github.com/cncf/contribute) - @elsony
  - [x] Add artwork to [CNC artwork](https://github.com/cncf/artwork) - @elsony
  - [ ] Transfer domain (devfile.io) to CNCF ([JIRA](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63)) - @elsony
  - [x] Maintainers: Andreas, Angel, Elson, Ida, Mario, Stevan, Tomas ([devfile PR](https://github.com/devfile/api/pull/746), [toc PR](https://github.com/cncf/foundation/pull/287)) @l0rd 
  - [ ] [Transfer trademark and logo mark over to CNCF (not registered)](https://github.com/cncf/foundation/blob/main/agreements/CNCF%20Trademark%20and%20Account%20Assignment%20Agreement%20(2020%20-%20no%20reg%20trademarks).pdf) ==\> ask legal - @elsony 
  - [x] 'thelinuxfoundation' and 'caniszczyk' as org owner - @l0rd 
  - [x] enable [DCO GitHub action](https://github.com/apps/dco) for the org - @l0rd 
  - [ ] reference [CNCF CoC](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) in Readme’s - @l0rd 
  - [x] [Website LF footer](https://github.com/devfile/api/issues/1736) - @elsony
  - [x] Transfer analytics to [amye@linuxfoundation.org](amye@linuxfoundation.org) - @elsony
  - [ ] CII [Best practice badge](https://bestpractices.coreinfrastructure.org/en) - @l0rd

**Comment by l0rd** [comment]
@rtaniwa @elsony @slemeur @resios I have updated this issue with a list of subtasks to complete to submit the proposal.

**Comment by rtaniwa** [comment]
Marking the logo complete. @elsony will share the design at one of the upcoming cabals.

**Comment by elsony** [comment]
Analytics transfer requirement done: https://github.com/cncf/toc/issues/773#issuecomment-1035389764

**Comment by elsony** [comment]
Added CNCF project contribution: https://github.com/cncf/contribute/pull/94

**Comment by elsony** [comment]
Added devfile artworks: https://github.com/cncf/artwork/pull/327

**Comment by vishaltak** [comment]
To work with DevWorkspace Operator, we need editor and editor injectors. Currently, the editors are in a different project(eclipse-che/che-incubator) and are differently licensed. For example, if we were to follow the [devworkspace-demo](https://github.com/l0rd/devworkspace-demo), it uses the following projects

- [Che-Code](https://github.com/che-incubator/che-code)
- [Jetbrains IDE](https://github.com/che-incubator/jetbrains-editor-images)

There are some other editors which are being used in the demo but they would mostly be out-of-scope for this.
- [TTYD](https://github.com/tsl0922/ttyd)
- [Che Theia](https://github.com/eclipse-che/che-theia)


It would be really helpful to have at least the Che-Code and Jetbrains IDE projects move from che-incubator to devfile while we are submitting the proposal to CNCF. I suspect it might involve more work that just transferring the repository. Let me know if it would be better to move this to a separate issue.

**Comment by michael-valdron** [comment]
Some requirements left to fulfill in order to be fully onboarded as a CNCF project.
