### ISSUE TITLE
Introduce new component 'helm'

### ISSUE THREAD

**Issue by sbose78** [devfile/api#53]
/kind user-story
/kind epic

## Which area this user story is related to?

/area api
/area library
/area integration-tests
/area test-automation

## User Story

As a stack/devfile author, I wish to provide deployment guidance in the form of a Helm Chart
```
---
components:
  - id: deploy-node-app
    helm:
      chart: http://helm-chart-url
      values: 
        image: quay.io/sample/hello-world # A chart may expose a well-known values.yaml parameter called "image".
        replicas: 3
```

If the `helm` component  is associated with a `dockerfile` component (image build guidance) in a `composite` command, https://github.com/devfile/kubernetes-api/issues/51 , che/odo must associate the built image from the 'build' guidance using the `image` parameter in the chart's values.yaml . 

```
- composite:
      id: build-and-deploy
      label: Build image and deploy nodejs app
      commands:
      - build-node-app
      - deploy-node-app
      parallel: false
      group: 
          kind: deploy
```

## Acceptance Criteria

- [ ] Introduce new component 'helm' to Devfile API
- [ ] Introduce new component 'helm' to Devfile Parser
- [ ] Introduce calls related to new component 'helm' in Devfile Library
- [ ] Validation for new component 'helm'
- [ ] Guide for using component 'helm'

refined by: @michael-valdron
