### ISSUE TITLE
Registry UI Improvement checklist

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#592]
**Which area/kind this issue is related to?**

/area registry

## Issue Description

Checklist for Registry UI https://registry.devfile.io/viewer Improvments

- [ ] Less white space between Filter field and values
- [ ] Devfile Header logo disappears
- [ ] Devfile Type (stack/sample) should be more subtle on the tile card

**Comment by jc-berger** [comment]
Very cool! Only thing that stood out to me was that I couldn't open the samples or stacks in a new tab/window. Not that I think that's a big deal. I, personally, default to right-clicking to open new tabs. 

Very easy to use UI!

**Comment by dharmit** [comment]
> Less white space between Filter field and values

Does this include the "Filter Types" and "Tags" showing up on the extreme left? Attached a screenshot. I'm on Firefox.

![image](https://user-images.githubusercontent.com/713521/130006545-80aec57e-0686-4668-853e-4374dde6cf5b.png)

**Comment by michael-valdron** [comment]
This seems to be implemented and resolved in PR devfile/devfile-web#40.
