### ISSUE TITLE
Landing Page devfile.io improvement checklist

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#602]
**Which area/kind this issue is related to?**

/area landing-page

## Issue Description

This list will host the aggregated checklist for landing page devfile.io improvements.

- [ ] Get Started Page for each persona should have their own webpage URLs, currently its served at one endpoint
- [ ] It should be responsive and be able to render properly esp on a mobile view
- [ ] https://github.com/devfile/api/issues/603

**Comment by rtaniwa** [comment]
Some feedback from the UXD team that we should discuss/assess. 

Landing page:
- Top navigation links 'Docs' and 'Devfile Registry' will take the user to external pages - maybe we need to indicate them with an external icon or any other way.  OR Do you think we need to segregate them like  'Getting Started'      l     'Docs' & 'Devfiles? 
- Is there any reason to have 4 sub titles in blue shade?  Can't we just have them in regular black color text?
- Under the 'Key Features' I assume the wheel icon is just the place holder, maybe align them with the rest of the content towards the left side.

Getting Started page:
- No visual indication we are on the Getting Started page. We need to indicate the 'Getting Started' as selected, maybe retain the blue color horizontal line once the user clicks on it.
- Left navigation looks a bit heavy for me because of a lot of information.  I would advise you to go with white background.  (assuming that we are not sticking to Patternfly style guides)
- Let Navigation interactions are a little confusing, do we need to expand and collapse them? 
- Is the content on the landing area a placeholder?  The subtitles font size can be reduced, now they look a little big and too many subtitles make it look very busy.

**Comment by rtaniwa** [comment]
Also we should look at providing some variety from the "gears" icon. I feel there is a bit of overuse of it on our page. :)  There are a number of free to use options we should explore.

**Comment by schultzp2020** [comment]
N/A after the landing page redesign
