### ISSUE TITLE
Update the build pipeline to use new Registry Viewer

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#747]
**Which area/kind this issue is related to?**

/area registry

## Issue Description
Update the Registry Viewer build pipeline to produce container images to use.

- [x] Registry Viewer build updated devfile/devfile-web#51
- [x] Registry Server build updated devfile/registry-support#147
- [x] Registry OpenShift Template updated devfile/registry#149
- [ ] Registry Operator updated devfile/registry-operator#28
- [x] Update Registry Viewer to include new environment variables (@schultzp2020)
## Related Issues
~Block by https://github.com/devfile/api/issues/720~ No longer blocked.

**Target Date: 12-20-2022**

**Comment by johnmcollier** [comment]
Closing

**Comment by michael-valdron** [comment]
blocked by PR devfile/devfile-web#48
