### ISSUE TITLE
Devfile 2.2 GA release tasks

### ISSUE THREAD

**Issue by elsony** [devfile/api#945]
**Which area/kind this issue is related to?**
/area releng

## Issue Description
As discussed on the devfile community call on 9/26, we'll go ahead with the GA release of the devfile 2.2 specifications. This issue is the parent for all the devfile 2.2 release-related activities.

Pre-release tasks:
- [x] Cut release on devfile API for devfile 2.2 (https://github.com/devfile/api/blob/main/docs/proposals/versioning-and-release.md) (https://github.com/devfile/api/issues/954)
- [x] Cut release on devfile library to match the devfile specification (https://github.com/devfile/api/issues/955)
- [x] Expose multiple versions of the stack in the devfile registry viewer and provide a filter for specific schema versions (https://github.com/devfile/api/issues/950)
- [x] Add rules to the devfile contributing guide for a minimum of 1 year of keeping an older version of the stack (https://github.com/devfile/api/issues/951)
- [ ] Add telemetry for detecting usage of different versions of the stack (https://github.com/devfile/api/issues/956)

Post-release tasks:
- [ ] Formal announcement of devfile 2.2 release (slack, mailing lists (CNCF, developer))
- [ ] Stacks can create a new version of the stack to support devfile 2.2 features. The existing devfile 2.1 should remain in the devfile registry using the registry multi-version support.
- [ ] Blog post for devfile 2.2 declaration
- [ ] Find out conferences
- [ ] Find out if CNCF has some newsletter or communication channel

**Comment by elsony** [comment]
Devfile 2.2 has been GAed for a while. The main outstanding item in this Epic is https://github.com/devfile/api/issues/956 for which we'll just track it using that issue directly.
