### ISSUE TITLE
Update deprecated Node.js 12 actions in devfile repos

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#992]
## Which area/kind this issue is related to?

/area releng

## Issue Description

[Node.js v12 has been removed from the Github action runner ](https://github.blog/changelog/2023-07-17-github-actions-removal-of-node12-from-the-actions-runner/)but a number of our repos still rely on this deprecated version.  We should update to the latest v16 version of the gitub actions and ensure actions are pinned to their commit hash: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

The following repos should be inspected for deprecated actions:

- [x] api https://github.com/devfile/api/issues/1224
- [x] library https://github.com/devfile/api/issues/1225
- [x] registry-support https://github.com/devfile/api/issues/1226
- [x] registry https://github.com/devfile/api/issues/1227
- [x] devfile-web https://github.com/devfile/api/issues/1228
- [x] integration-tests https://github.com/devfile/api/issues/1229

**Comment by thepetk** [comment]
@kim-tsao should we treat #1230 as an independent item, as it is handled externally, and close EPIC 992?

**Comment by thepetk** [comment]
@kim-tsao I've removed the last item https://github.com/devfile/api/issues/1230 as it wasn't handled by the devfiles team. As all other items have been closed I'll close this epic too.

**Comment by kim-tsao** [comment]
> @kim-tsao should we treat #1230 as an independent item, as it is handled externally, and close EPIC 992?

Yes, let it be an independent item
